# This file was generated by GoReleaser. DO NOT EDIT.
cask "qcloud" do
  version "0.26.0"

  on_macos do
    on_intel do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-darwin-amd64.tar.gz"
      sha256 "0802522c178f8d5e084be01ff72b47e178fd6edde97133f02ac45aa29845cbfa"
    end
    on_arm do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-darwin-arm64.tar.gz"
      sha256 "13787b53aac4762d718243c2f4ba0a089952b3c7b96c58a195d486b17251d1e9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-linux-amd64.tar.gz"
      sha256 "05b896ebeb9b8ef46c1d14c07114cbe62c55ad4c3a38f456d1eb7e798fb119d5"
    end
    on_arm do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-linux-arm64.tar.gz"
      sha256 "53f8d6efb5f461285a5c4d7f48c9c1ec23a6e3c1ed24532e9554318a53539f90"
    end
  end

  name "qcloud"
  desc "The Command Line Interface for Qdrant Cloud"
  homepage "https://github.com/qdrant/qcloud-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qcloud"
  generate_completions_from_executable "qcloud",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
