# This file was generated by GoReleaser. DO NOT EDIT.
cask "qcloud" do
  version "0.24.2"

  on_macos do
    on_intel do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-darwin-amd64.tar.gz"
      sha256 "3b0818f9f4d2d09f79df4d3309a502e58e1bc860c81c3324e364c510a37cf782"
    end
    on_arm do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-darwin-arm64.tar.gz"
      sha256 "40b0d78762a30c19f0d7e06c8d82d84dab86ab7c750c84d240f84aa347fb7e04"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-linux-amd64.tar.gz"
      sha256 "551cfc6d5e55634d5030bf54fe9d44aefaae09f392e78c9457b092d68996047e"
    end
    on_arm do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-linux-arm64.tar.gz"
      sha256 "b75d2535d396c74569b83ceb9aa6fb817a17f63a5484007ceb4eb0cc727d7449"
    end
  end

  name "qcloud"
  desc "The Command Line Interface for Qdrant Cloud"
  homepage "https://github.com/qdrant/qcloud-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qcloud"
  generate_completions_from_executable "qcloud",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
