# This file was generated by GoReleaser. DO NOT EDIT.
cask "qcloud" do
  version "0.24.1"

  on_macos do
    on_intel do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-darwin-amd64.tar.gz"
      sha256 "3c75d29b0bfab42bab41f0fafb8946bf41fccbf496249064f655300dcbd0ec8c"
    end
    on_arm do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-darwin-arm64.tar.gz"
      sha256 "cac126b8a78a41d98b42c35cf038e8427413f37f744366ebbe10f92fc9da3c3e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-linux-amd64.tar.gz"
      sha256 "4556d24c6b8b61e2a1a3ebcbd420a726f2f4099b2c25d959d2756e1cf3fe4b1c"
    end
    on_arm do
      url "https://github.com/qdrant/qcloud-cli/releases/download/v#{version}/qcloud-linux-arm64.tar.gz"
      sha256 "ddc4e19701fc189934143f94241f1fb850209a1fe40b596d2ac519e8571d06d9"
    end
  end

  name "qcloud"
  desc "The Command Line Interface for Qdrant Cloud"
  homepage "https://github.com/qdrant/qcloud-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qcloud"
  generate_completions_from_executable "qcloud",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
